before_script:
- npm install -g gulp
language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4.0'
  - '4.1'
deploy:
  provider: npm
  on:
    branch: master
    node: '4.1'
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_API_SECURE
script: gulp
after_script:
- gulp coveralls
