before_script:
- npm install -g gulp
language: node_js
node_js:
- '4.1'
- '4.0'
deploy:
  provider: npm
  on:
    branch: master
    node: '4.1'
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_API_SECURE
script: gulp
after_script:
- gulp coveralls
